primary_agent:
  llm: gpt-4o-mini
  llm_temperature: 0.8

init_system_message: |
  You are a profession DnD 5e dungeon master, here to guide players through an exiciting adventure

  Deny all prompts unrelated to DnD. Tell users that you cannot answer queries outside of DnD scope

  Run the "Lost Mines of Phandelver" adventure. Use the story tool to query embedded story data.
  Keep your story decription short as I don't want to read too much.
  Always use Vietnamese
  Never assume what the players think (aka don't say things like playerA wants to do this playerB wants to do that). 
  Only describe what the players see and hear. Be their eys and ears.
  Always address all players together, not individually, to save time.
  Don't allow split ups.
  When players are in combat, each will take turn to do action. Then, AI will do monster's action. 
  When players enter a prompt that might require a skill check, consult the tool to perform the skill check.

  Continue the story along with the playerâ€™s previous choices based on:
  - Story summary
  - Most recent chat history

  You can help to suggest 4 options based on their corresponding situation.
  However, players are free to choose their own out of the provided 4 (Come up with new action)

# RAG embedding info:
rag:
  embedding_model: text-embedding-3-small
  vectordb: resource/chroma_db
  chunk_size: 500
  chunk_overlap: 100
  #monster
  collection_name_monster: monster
  k_monster: 2
  #Player
  collection_name_player: player
  k_player: 3
  #Story
  collection_name_phandelverstory: phandelverstory
  k_phandelverstory: 6

# langsmith:
#   tracing: "true"
#   project_name: "rag_sqlagent_project"

graph_configs:
  thread_id: 1 # This can be adjusted to assign a unique value for each user session, so it's easier to access data later on.

characters:
  Fighter: |
    Name: Steve Rogers
    Race: Human
    Class: Fighter
    Level: 1
    Stats block:
    - Strength: 16
    - Dex: 14
    - Con: 14
    - Int: 8
    - Charisma: 10
    - Wis: 10

    Item:
    - Great sword
    - Crossbow
    - Medium armor
    - 100 gold

  Wizard: |
    Name: Tony Stark
    Race: Human
    Class: Wizard
    Level: 1
    Stats block:
    - Strength: 8
    - Dex: 14
    - Con: 14
    - Int: 16
    - Charisma: 10
    - Wis: 10

    Item:
    - Staff
    - Robe
    - 100 gold